<?php
namespace app\controllers;
use app\models\LoginForm;
use yii\rest\ActiveController;
use yii;
use yii\helpers\ArrayHelper;
use yii\filters\auth\QueryParamAuth;

class UserController extends ActiveController
{
    public $modelClass = 'api\models\User';

    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }

    public function actionIndex()
    {
        //Ваш код
    }
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticatior' => [
            'class' => QueryParamAuth :: className (), // Реализуем аутентификацию токена доступа
            'except' => ['login'], // Нет необходимости проверять метод токена доступа, обратите внимание, чтобы различать $ noAclLogin
            ]
        ]);
    }
    public function actionTest()
    {
        return ['status'=>'success'];
    }
    /**
    * Авторизоваться
    * @return array
    * @throws \yii\base\Exception
    * @throws \yii\base\InvalidConfigException
    */
    public function actionLogin()
    {
        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->getBodyParams(), '') && $model->login()) {
            return [
                'access_token' => $model->login(),
            ];
        } else {
            return $model->getFirstErrors();
        }
    }
}